# Generated by Django 5.1.1 on 2024-10-06 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Women',
        ),
    ]
